/** Verified icon sources — local first, then CDN fallbacks. */
export const SKILL_ICON_URLS: Record<string, string> = {
  react: "https://cdn.simpleicons.org/react/61DAFB",
  typescript: "https://cdn.simpleicons.org/typescript/3178C6",
  javascript: "https://cdn.simpleicons.org/javascript/F7DF1E",
  python: "https://cdn.simpleicons.org/python/3776AB",
  nextjs: "https://cdn.simpleicons.org/nextdotjs/ffffff",
  tailwind: "https://cdn.simpleicons.org/tailwindcss/06B6D4",
  figma: "https://cdn.simpleicons.org/figma/F24E1E",
  framer: "https://cdn.simpleicons.org/framer/0055FF",
  openai: "https://cdn.jsdelivr.net/npm/simple-icons@11.14.0/icons/openai.svg",
  java: "https://cdn.simpleicons.org/openjdk/ED8B00",
  html5: "https://cdn.simpleicons.org/html5/E34F26",
  css: "https://cdn.simpleicons.org/css/1572B6",
  nodedotjs: "https://cdn.simpleicons.org/nodedotjs/339933",
  github: "https://cdn.simpleicons.org/github/ffffff",
  git: "https://cdn.simpleicons.org/git/F05032",
  vite: "https://cdn.simpleicons.org/vite/646CFF",
  streamlit: "https://cdn.simpleicons.org/streamlit/FF4B4B",
  huggingface: "https://cdn.simpleicons.org/huggingface/FFD21E",
  postgresql: "https://cdn.simpleicons.org/postgresql/4169E1",
  illustrator: "/assets/skills/illustrator.svg",
  photoshop: "/assets/skills/photoshop.svg",
  aftereffects: "/assets/skills/aftereffects.svg",
  canva: "https://cdn.jsdelivr.net/npm/simple-icons@11.14.0/icons/canva.svg",
  vercel: "https://cdn.simpleicons.org/vercel/ffffff",
  davinciresolve: "https://cdn.simpleicons.org/davinciresolve/FF0000",
};

export const SKILL_ICON_SIZES: Record<string, number> = {
  react: 58,
  typescript: 56,
  javascript: 56,
  python: 56,
  nextjs: 54,
  tailwind: 56,
  figma: 54,
  framer: 54,
  openai: 54,
  java: 54,
  html5: 54,
  css: 54,
  nodedotjs: 54,
  github: 54,
  git: 54,
  vite: 54,
  streamlit: 52,
  huggingface: 54,
  postgresql: 54,
  illustrator: 54,
  photoshop: 54,
  aftereffects: 54,
  canva: 52,
  vercel: 52,
  davinciresolve: 52,
};

export const SKILL_ICON_IDS = Object.keys(SKILL_ICON_URLS);
